create table if not exists public.category_operation_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  target_type text not null,
  target_id bigint,
  target_name text,
  before_data jsonb,
  after_data jsonb,
  actor text,
  created_at timestamp with time zone not null default now()
);

create index if not exists category_operation_logs_created_at_idx
  on public.category_operation_logs (created_at desc);

create index if not exists category_operation_logs_action_idx
  on public.category_operation_logs (action);
