create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  unique (category_id, name)
);

insert into public.categories (name, sort_order)
select category_name, row_number() over (order by category_name) - 1
from (
  select distinct unnest(category) as category_name
  from public.games
  where category is not null
) source
where category_name is not null
  and trim(category_name) <> ''
on conflict (name) do nothing;

insert into public.subcategories (category_id, name, sort_order)
select
  c.id,
  source.subcategory_name,
  row_number() over (partition by c.id order by source.subcategory_name) - 1
from (
  select distinct
    unnest(category) as category_name,
    unnest(subcategory) as subcategory_name
  from public.games
  where category is not null
    and subcategory is not null
) source
join public.categories c on c.name = source.category_name
where source.subcategory_name is not null
  and trim(source.subcategory_name) <> ''
on conflict (category_id, name) do nothing;
