create table if not exists public.home_category_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.home_category_group_items (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.home_category_groups(id) on delete cascade,
  subcategory_id bigint not null references public.subcategories(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  unique (group_id, subcategory_id)
);

insert into public.home_category_groups (name, sort_order)
select name, sort_order
from public.categories
where not exists (select 1 from public.home_category_groups)
order by sort_order, id;

insert into public.home_category_group_items (group_id, subcategory_id, sort_order)
select
  g.id,
  s.id,
  row_number() over (partition by g.id order by s.sort_order, s.id) - 1
from public.home_category_groups g
join public.categories c on c.name = g.name
join public.subcategories s on s.category_id = c.id
where not exists (
  select 1
  from public.home_category_group_items existing
  where existing.group_id = g.id
);
